spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://trucknest.duckdns.org/auth/realms/trucknest
          jwk-set-uri: http://keycloak:8080/realms/trucknest/protocol/openid-connect/certs

server:
  forward-headers-strategy: framework

logging:
  level:
    com.trucknest: DEBUG
    org.springframework.security: DEBUG
    org.keycloak: DEBUG
    root: INFO
